In [1]:
import numpy as np

In [3]:
l = [1,2,3,4]
a = np.array(l, np.int)
print(a)
b = np.array(l, np.float)
print(b)
c = np.array(l, np.str)
print(c)

[1 2 3 4]
[1. 2. 3. 4.]
['1' '2' '3' '4']


In [4]:
a = np.array([1,2,3,4])
b = np.array([[1,2], [3,4]])
print(a.ndim, b.ndim)
print(a.shape, b.shape)

1 2
(4,) (2, 2)


In [5]:
c = np.array([[1,2],[3,4],[5,6]])
print(c.shape)

(3, 2)


In [13]:
a= np.array([1,2,3,4])
s=a
print(a)
print(s)

[1 2 3 4]
[1 2 3 4]


In [14]:
# 원본 유지 방법
ss = a.copy()
print(ss)

[1 2 3 4]


In [15]:
s[0]=99
print(a)
print(s)

[99  2  3  4]
[99  2  3  4]


In [17]:
import math
import numpy as np

In [19]:
x = np.array([2,2])
mag = lambda x:math.sqrt(sum(val**2 for val in x))
print(mag(x))

2.8284271247461903


In [20]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],[10,20,30] ])
print(a2.shape)

(2, 3)


In [21]:
a3 = np.array([[[1,2,3]]])

In [1]:
import numpy as np
import time
size_of_vec = 10000000

def pure_python_version():
  t1 = time.time()
  X = range(size_of_vec)
  Y = range(size_of_vec)
  Z = []
  for i in range(len(x)):
    Z.append(X[i] * Y[i])
  print(t1)
  return time.time() - t1

def numpy_version():
  t2 = time.time()
  X = np.arange(size_of_vec)
  Y = np.arange(size_of_vec)
  Z = X + Y
  print(t2)
  return time.time() - t2

t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)

NameError: name 'x' is not defined

In [7]:
l = [1,2,3,4,5,7]
a = np.array(l)
print(a)

[1 2 3 4 5 7]


In [6]:
print('1:',type(1))
print('2:',a.ndim)
print('3:',a.shape)
print('4:',a.size)
print('5:',a.dtype)
print('6:',a.itemsize)
print('7:',a.data)

1: <class 'int'>
2: 1
3: (5,)
4: 5
5: int32
6: 4
7: <memory at 0x000001E8E4D6AB88>


In [11]:
import math
x =np.array([3,4])
mag = lambda x:math.sqrt(sum(val**2 for val in x))
print(mag(x))

5.0


In [12]:
def result(list):
    sum_all = 0
    for val in list:
        result = val **2
        sum_all = sum_all + result
    rel = math.sqrt(sum_all)
    return rel
x = np.array([2,2])
result(x)

2.8284271247461903

In [25]:
a = np.array([1,3,5])
b = np.array([1,2])
(a.T).dot(b)

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

In [26]:
a= np.matrix([[1,2],[3,4]])
b= np.matrix([[5,6],[7,8]])
a.dot(b)

matrix([[19, 22],
        [43, 50]])

In [28]:
c= np.matrix([[5,6], [7,8]])
d= np.matrix([[1,2], [3,4]])
c*d

matrix([[23, 34],
        [31, 46]])

In [30]:
e = np.array([[1,3,5]]).T
f = np.array([[1,2]])
e.dot(f)

array([[ 1,  2],
       [ 3,  6],
       [ 5, 10]])

In [31]:
e.shape

(3, 1)

In [32]:
g=np.array([[1,3,5,],])

In [33]:
g.shape

(1, 3)

In [36]:
h= np.array([[,[1,3,5]]])
h.shape

SyntaxError: invalid syntax (<ipython-input-36-a86aab72edec>, line 1)

In [37]:
q=np.array([[60, 5.5, 1],[54, 5.0, 0], [55, 6.0, 1]])
q.shape

(3, 3)

In [38]:
w = np.array([[66,74,78]]).T
w.shape

(3, 1)

In [40]:
import math
import numpy as np

a= np.array([4,5])
b= np.array([3,8])
f=a+b
g=a-b
print(f,g)

[ 7 13] [ 1 -3]


In [41]:
l = [1,2,3,4]
a=np.array(l, np.int)
a

array([1, 2, 3, 4])

In [42]:
l3 = [[1,2,3],[4,5,6],[7,8,9]]
n3 = np.array(l3, np.int)
n3


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
n3[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [44]:
data = np.random.randn(3,2,2)
data

array([[[ 1.07632298, -1.18114743],
        [ 0.13139177,  1.12951614]],

       [[-1.66878704,  0.83962295],
        [ 0.29167161,  1.07606924]],

       [[-0.56918285, -0.70045765],
        [ 0.59001169, -0.18040562]]])

In [45]:
data2 = np.random.randn(3,2,2,3)
data2

array([[[[-1.24583134e+00,  2.46702754e+00,  1.54851025e+00],
         [-2.56881772e+00, -2.40777036e-01, -3.71306576e-01]],

        [[-5.44080142e-01, -8.66962650e-01,  6.37176575e-01],
         [-1.39998637e+00, -4.31104709e-01, -5.09976033e-01]]],


       [[[ 3.27317809e-01,  2.29733111e-01,  1.14989840e+00],
         [-6.13595103e-01,  6.20779803e-02,  2.79249422e-01]],

        [[ 8.59705450e-04,  1.41460012e+00,  3.54737635e-01],
         [ 1.62939844e+00, -9.49460002e-02,  2.76076038e+00]]],


       [[[ 8.07523344e-01, -5.52334207e-01,  6.35204231e-01],
         [ 1.68564342e+00,  1.58347619e+00,  3.62668355e-01]],

        [[ 1.23518264e+00,  5.44598814e-01,  9.15574599e-01],
         [ 6.60322487e-01, -2.68886810e-01,  7.44667001e-01]]]])

In [46]:
f = np.array([1.0, 2.0, 3.0])
a = f > 2.0
a

array([False, False,  True])

In [49]:
f = np.array(['male', 'female', 'male'])
a = f =='male'
print(a)
print(f[a]) 

[ True False  True]
['male' 'male']


In [50]:
import numpy as np
f = np.arange(0, 12)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
a= f.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
a[1,1:3]

array([5, 6])

In [55]:
a[a>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
a>3

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])