In [0]:
#1
import numpy as np 

In [2]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [3]:
c.shape

(3,)

In [4]:
c=np.array([[1,2,3]])
c.shape

(1, 3)

In [5]:
c= np.array([[1,2,3], [4,5,6]])
c.shape

(2, 3)

In [7]:
a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [8]:
a=np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [10]:
a=np.full((2,2), 10)
a

array([[10, 10],
       [10, 10]])

In [11]:
b = np.array([[11,12,13,14], [15,16,17,18]])
b

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [12]:
b.shape

(2, 4)

In [13]:
b.T

array([[11, 15],
       [12, 16],
       [13, 17],
       [14, 18]])

In [14]:
a=np.array([[1,2], [3,4], [5,6]])
a.shape

(3, 2)

In [15]:
c=a.dot(b)
c.shape

(3, 4)

In [16]:
c

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [17]:
np.dot(a,b)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [18]:
np.dot(b.T, a.T)

array([[ 41,  93, 145],
       [ 44, 100, 156],
       [ 47, 107, 167],
       [ 50, 114, 178]])

In [19]:
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
eye4 = np.eye(4)
eye4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
#2
import numpy as np

In [22]:
c= np.array([1,2,3])
c.shape

(3,)

In [0]:
c=np.array([[1,2,3]])

In [24]:
c.shape

(1, 3)

In [25]:
c=np.array([[1,2,3], [4,5,6]])
c.shape

(2, 3)

In [26]:
### zero vector
a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [27]:
a=np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [28]:
a=np.full((2,2),10)
a

array([[10, 10],
       [10, 10]])

In [29]:
b=np.array([[11,12,13,14], [15,16,17,18]])
b

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [30]:
b.shape

(2, 4)

In [31]:
# transpose a matrix
# 전치 행렬
b.T

array([[11, 15],
       [12, 16],
       [13, 17],
       [14, 18]])

In [32]:
a=np.array([[1,2], [3,4], [5,6]])
a.shape

(3, 2)

In [0]:
c=a.dot(b)

In [34]:
c.shape

(3, 4)

In [35]:
c

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [36]:
np.dot(a,b)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [37]:
np.dot(b.T, a.T)

array([[ 41,  93, 145],
       [ 44, 100, 156],
       [ 47, 107, 167],
       [ 50, 114, 178]])

In [39]:
eye3=np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
eye4=np.eye(4)
eye4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
#3
import numpy as np
c = np.array([1,2,3])
c.shape

(3,)

In [42]:
c=np.array([[1,2,3]])
c.shape

(1, 3)

In [48]:
c=np.array([[1,2,3], [4,5,6]])
print(c.shape)
print(type(c))

(2, 3)
<class 'numpy.ndarray'>


In [44]:
a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [45]:
a=np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [46]:
a=np.full((2,2), 10)
a

array([[10, 10],
       [10, 10]])