In [0]:
import numpy as np

In [3]:
c = np.array( [1,2,3]  )
c.shape

(3,)

In [4]:
c = np.array([ [1,2,3] ] )
c.shape

(1, 3)

In [5]:
c = np.array([ [1,2,3], [4,5,6] ]  )
c.shape

(2, 3)

In [6]:
### zero vector
a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [8]:
a=np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [10]:
a=np.full((2,2),10)
a

array([[10, 10],
       [10, 10]])

In [0]:
b=np.array([[11,12,13,14], [15,16,17,18]])

In [12]:
b

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [13]:
b.shape

(2, 4)

In [14]:
# transpose a matrix
# 전치행렬
b.T

array([[11, 15],
       [12, 16],
       [13, 17],
       [14, 18]])

In [15]:
## A 행렬 1,2
##        3,4
##        5,6
##        2*3
a=np.array([[1,2], [3,4], [5,6]])
a.shape

(3, 2)

In [0]:
c=a.dot(b)

In [18]:
c.shape

(3, 4)

In [19]:
c

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [20]:
np.dot(a,b)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [22]:
np.dot(b.T, a.T)

array([[ 41,  93, 145],
       [ 44, 100, 156],
       [ 47, 107, 167],
       [ 50, 114, 178]])

In [23]:
### 항등행렬
### identity matrix
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
eye4 = np.eye(4)
eye4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
# 역행렬 만들기
from numpy.linalg import inv

In [0]:
A=np.array([[60, 5.5, 1],[65, 5.0, 0],[55, 6.0, 1]])
b=np.array([[66, 70, 78]]).T

In [37]:
b.shape

(3, 1)

In [27]:
A_inv = inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [28]:
A.dot(A_inv)

array([[ 1.0000000e+00,  0.0000000e+00, -4.4408921e-16],
       [ 8.8817842e-16,  1.0000000e+00, -8.8817842e-16],
       [-8.8817842e-16,  0.0000000e+00,  1.0000000e+00]])

In [0]:
# AX=b
# X=A-*b
X=A_inv.dot(b)

In [39]:
X

array([[ -0.43478261],
       [ 19.65217391],
       [-16.        ]])

In [40]:
# X 바로 구해주는 매쏘드
from numpy.linalg import solve
x=solve(A,b)
x

array([[ -0.43478261],
       [ 19.65217391],
       [-16.        ]])

In [44]:
import numpy as np

f = np.arange(0,12).reshape(2,3,2)
print(f)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
