## MNIST 데이터를 이용한 신경망 문제 풀이

In [0]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

In [17]:
mnist = input_data.read_data_sets('./mnist/data', one_hot=True)

Extracting ./mnist/data/train-images-idx3-ubyte.gz
Extracting ./mnist/data/train-labels-idx1-ubyte.gz
Extracting ./mnist/data/t10k-images-idx3-ubyte.gz
Extracting ./mnist/data/t10k-labels-idx1-ubyte.gz


In [18]:
mnist = input_data.read_data_sets('./mnist/data', one_hot=True)
print(mnist.train.labels[1])

Extracting ./mnist/data/train-images-idx3-ubyte.gz
Extracting ./mnist/data/train-labels-idx1-ubyte.gz
Extracting ./mnist/data/t10k-images-idx3-ubyte.gz
Extracting ./mnist/data/t10k-labels-idx1-ubyte.gz
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## 02. 신경망 모델 구성
* 28*28 픽셀 -> 784개의 특징
* Label은 0~9까지 10개의 분류
* 입력 X, 출력 Y
* None에는 이미지의 개수를 지정하는 값이 들어간다.

In [0]:
X = tf.placeholder(tf.float32, [None, 784]) # 입력
Y = tf.placeholder(tf.float32, [None, 10]) # 범주의 수

## 우리가 만들 신경망
* 784개의 특징(입력)
* 256(첫 번째 은닉킁의 뉴런 개수)
* 256(두 번째 은닉층의 뉴런 개수)
* 10(결과값 0-9 분류의 개수)

In [0]:
## 784개의 입력, 256개의 뉴런
## 표준편차가 0.01인 정규분포를 가지는 임의의 뉴런을 초기화 시킨다.
W1 = tf.Variable(tf.random_normal([784, 256], stddev=0.01))

## X(입력값)에 가중치를 곱하고, 이후 ReLU 함수를 이용하여 레이어를 만든다.
L1 = tf.nn.relu(tf.matmul(X, W1)) # 데이터수?*784 X 784*256 => 데이터수 *256

##
W2 = tf.Variable(tf.random_normal([256, 256], stddev=0.01))
# L1(입력값)에 가중치를 곱하고, 이후 ReLU함수를 이용해서 레이어를 만든다.
L2 = tf.nn.relu(tf.matmul(L1, W2)) # 데이터수*256(L1) X 256*256 => 데이터수*256)
                
W3 = tf.Variable(tf.random_normal([256, 10], stddev=0.01))
model = tf.matmul(L2, W3) #데이터 수*256(L2)x256*10 => 데이터수*10


## cost 함수와 최적화 알고리즘을 정한다.

In [0]:
cost = tf.reduce_mean(tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=model, labels=Y)))
optimizer = tf.train.AdamOptimizer(0.001).minimize(cost)

In [0]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [0]:
batch_size =100
total_batch=int(mnist.train.num_examples/batch_size)

In [25]:
for epoch in range(15):
  total_cost = 0
  for i in range(total_batch):
    batch_xs, batch_ys = mnist.train.next_batch(batch_size) # 학습할 데이터를 가져온다.
    
    # 입력 X, 출력 Y에 각각의 데이터 넣고 실행
    _, cost_val = sess.run([optimizer,cost],
                          feed_dict={X:batch_xs, Y:batch_ys})
    total_cost += cost_val
  print(batch_xs.shape, batch_ys.shape)
  print('Epoch {}, Avg. cost = {}'.format(epoch+1, total_cost/total_batch))

(100, 784) (100, 10)
Epoch 1, Avg. cost = 0.4096947777271271
(100, 784) (100, 10)
Epoch 2, Avg. cost = 0.15325447208163412
(100, 784) (100, 10)
Epoch 3, Avg. cost = 0.09593705082481557
(100, 784) (100, 10)
Epoch 4, Avg. cost = 0.07038132255896926
(100, 784) (100, 10)
Epoch 5, Avg. cost = 0.05424531623551791
(100, 784) (100, 10)
Epoch 6, Avg. cost = 0.04015786610797725
(100, 784) (100, 10)
Epoch 7, Avg. cost = 0.03036132561847229
(100, 784) (100, 10)
Epoch 8, Avg. cost = 0.025817822343775665
(100, 784) (100, 10)
Epoch 9, Avg. cost = 0.018677901674368926
(100, 784) (100, 10)
Epoch 10, Avg. cost = 0.01733220429773527
(100, 784) (100, 10)
Epoch 11, Avg. cost = 0.013861975048679266
(100, 784) (100, 10)
Epoch 12, Avg. cost = 0.013688170096508905
(100, 784) (100, 10)
Epoch 13, Avg. cost = 0.011962682794573166
(100, 784) (100, 10)
Epoch 14, Avg. cost = 0.013346888999453355
(100, 784) (100, 10)
Epoch 15, Avg. cost = 0.008776299235634558


In [26]:
model

<tf.Tensor 'MatMul_8:0' shape=(?, 10) dtype=float32>

In [27]:
Y

<tf.Tensor 'Placeholder_3:0' shape=(?, 10) dtype=float32>

In [28]:
# tf.argmax(model, 1)는  최대값을 뽑기
# tf.argmax(Y,1)는  최대값 뽑기
# 결과는 10개 레이블중에 확률이 가장 높은 값이 된다.
print(mnist.test.images.shape)
print(mnist.test.labels.shape)
is_correct = tf.equal(tf.argmax(model, 1), tf.argmax(Y,1)) 
is_correct
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
accuracy
print(model)
print(is_correct)
print(accuracy)

(10000, 784)
(10000, 10)
Tensor("MatMul_8:0", shape=(?, 10), dtype=float32)
Tensor("Equal:0", shape=(?,), dtype=bool)
Tensor("Mean_4:0", shape=(), dtype=float32)


In [29]:
print(mnist.test.images.shape)
print(mnist.test.labels.shape)
print('정확도', sess.run(accuracy, feed_dict={X:mnist.test.images,
                                              Y:mnist.test.labels}))

(10000, 784)
(10000, 10)
정확도 0.9812


In [31]:
import numpy as np
#a = np.[    ]

a = np.arange(100000).reshape(10000,10)
a


array([[    0,     1,     2, ...,     7,     8,     9],
       [   10,    11,    12, ...,    17,    18,    19],
       [   20,    21,    22, ...,    27,    28,    29],
       ...,
       [99970, 99971, 99972, ..., 99977, 99978, 99979],
       [99980, 99981, 99982, ..., 99987, 99988, 99989],
       [99990, 99991, 99992, ..., 99997, 99998, 99999]])

In [32]:
np.argmax(a,1)

array([9, 9, 9, ..., 9, 9, 9])

In [0]:
np.argmax(a,1)