## 01. Tensorflow 라이브러리 불러오기
## Tensorflow(google), Pytorch(facebook), Keras(가볍게 사용)


In [0]:
import tensorflow as tf

## 02. 값을 저장.
* Tensor 라는 자료형.
* shape() : 자료의 행, 열
* dtype(자료형) : 문자열

In [3]:
hello = tf.constant('hello, world!')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


### 03. 텐서플로우 생성.
* 그래프 생성과 그래프의 실행
* 그래프의 생성, 간단히 텐서와 텐서들의 연산 모음

In [5]:
a = tf.constant(10)
b = tf.constant(25)
c =tf.add(a, b)
print(c)
print(type(c))

Tensor("Add:0", shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.Tensor'>


In [6]:
## 그래프의 실행
sess = tf.Session()
print(sess.run(hello))
print(sess.run([a,b,c,]))

b'hello, world!'
[10, 25, 35]


## 3-3 플레이스 홀더와 변수
* 플레이스 홀더 : 나중에 값을 입력받기 위한 매개변수
* shape(?,3)은 두번째 차원요소가 3임을 의미

In [8]:
# None은 아직 정해지지 않았다는 뜻
X=tf.placeholder(tf.float32, [None, 3])
x_data = [[1,2,3],[4,5,6] ]
# print(X)

W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

expr = tf.matmul(X, W) + b
expr

<tf.Tensor 'add_1:0' shape=(2, 2) dtype=float32>

In [13]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print('=== x_data ===')
print(x_data)
print('=== W ===')
print(sess.run(W))
print('=== b ===')
print(sess.run(b))
print('=== expr ===')
print(sess.run(expr, feed_dict={X:x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[ 0.27114493 -0.59089327]
 [-0.03765481  0.71662015]
 [-1.7715995   0.39369765]]
=== b ===
[[ 0.7942963]
 [-0.911484 ]]
=== expr ===
[[ -4.324667    2.8177361]
 [-10.644775    2.6702297]]


# Regression

In [0]:
import tensorflow as tf
# y = WX +b

In [0]:
x_data = [1,2,3]
y_data = [1,2,3]

In [16]:
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
print(W)
print(b)

<tf.Variable 'Variable_2:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'Variable_3:0' shape=(1,) dtype=float32_ref>


In [0]:
X = tf.placeholder(tf.float32, name='X')
Y = tf.placeholder(tf.float32, name='Y')

In [18]:
## hypothesis : 가설
hypothesis = W*X + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
cost

<tf.Tensor 'Mean:0' shape=() dtype=float32>

## 2-5 최적화 함수(경사하강법)
 * 최적화 함수란 가중치(w)와 편향(b)을 변경해 가면서 손실값을 최소화시키는 가장 최적화된 가중치와 편향값을 찾아주는 함수.
 * 경사하강법(gradient descent)는 최적화 방법 중 가장 기본적인 알고리즘이다.
 * 경사하강법 : 함수의 기울기를 구하고, 기울기가 낮은 쪽으로 계속 이동시키면서 최적의 값을 찾아 나간다.

In [20]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
cost

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)
train_op

<tf.Operation 'GradientDescent' type=NoOp>

In [21]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  
  for step in range(100):
    _, cost_val = sess.run([train_op, cost], feed_dict={X:x_data, Y:y_data})
    print(step, cost_val, sess.run(W), sess.run(b))

0 0.2659602 [0.9071294] [0.26940498]
1 0.012749594 [0.88604665] [0.25267223]
2 0.009270241 [0.89133424] [0.24771912]
3 0.008795578 [0.893668] [0.24164161]
4 0.008377365 [0.89625454] [0.23584609]
5 0.0079794265 [0.89874524] [0.23017506]
6 0.007600408 [0.9011797] [0.22464195]
7 0.0072393753 [0.9035552] [0.2192417]
8 0.0068954993 [0.90587366] [0.21397127]
9 0.006567959 [0.90813637] [0.20882756]
10 0.006255973 [0.9103448] [0.2038075]
11 0.0059588123 [0.91249996] [0.19890809]
12 0.005675759 [0.9146034] [0.19412647]
13 0.005406165 [0.9166563] [0.18945983]
14 0.0051493673 [0.9186598] [0.18490534]
15 0.0049047596 [0.9206152] [0.18046035]
16 0.0046717827 [0.9225235] [0.17612219]
17 0.004449873 [0.924386] [0.17188835]
18 0.0042385007 [0.9262037] [0.16775627]
19 0.004037171 [0.92797774] [0.16372351]
20 0.0038454055 [0.92970914] [0.15978771]
21 0.0036627452 [0.93139887] [0.15594652]
22 0.003488756 [0.933048] [0.15219767]
23 0.0033230428 [0.9346575] [0.14853895]
24 0.0031651936 [0.9362283] [0.14496

In [22]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  
  for step in range(100):
    _, cost_val = sess.run([train_op, cost], feed_dict={X:x_data, Y:y_data})
    if step%10==0:
      print(step, cost_val, sess.run(W), sess.run(b))
      
    print('X:5, Y:', sess.run(hypothesis, feed_dict={X:5}))
    print('X:2.5, Y:', sess.run(hypothesis, feed_dict={X:2.5}))

0 0.92950886 [1.227247] [-0.40710765]
X:5, Y: [5.7291274]
X:2.5, Y: [2.66101]
X:5, Y: [5.473379]
X:2.5, Y: [2.528397]
X:5, Y: [5.4880357]
X:2.5, Y: [2.5417852]
X:5, Y: [5.473458]
X:2.5, Y: [2.539243]
X:5, Y: [5.4623876]
X:2.5, Y: [2.538468]
X:5, Y: [5.451238]
X:2.5, Y: [2.5375247]
X:5, Y: [5.440394]
X:2.5, Y: [2.5366242]
X:5, Y: [5.429807]
X:2.5, Y: [2.535744]
X:5, Y: [5.4194746]
X:2.5, Y: [2.5348845]
X:5, Y: [5.409391]
X:2.5, Y: [2.5340462]
10 0.016710503 [1.1465287] [-0.33309433]
X:5, Y: [5.3995495]
X:2.5, Y: [2.5332274]
X:5, Y: [5.3899446]
X:2.5, Y: [2.5324287]
X:5, Y: [5.3805704]
X:2.5, Y: [2.531649]
X:5, Y: [5.371422]
X:2.5, Y: [2.5308883]
X:5, Y: [5.3624935]
X:2.5, Y: [2.530146]
X:5, Y: [5.3537793]
X:2.5, Y: [2.5294213]
X:5, Y: [5.3452744]
X:2.5, Y: [2.5287137]
X:5, Y: [5.3369737]
X:2.5, Y: [2.5280232]
X:5, Y: [5.3288736]
X:2.5, Y: [2.52735]
X:5, Y: [5.3209677]
X:2.5, Y: [2.5266924]
20 0.010271537 [1.1148804] [-0.2611503]
X:5, Y: [5.313252]
X:2.5, Y: [2.5260508]
X:5, Y: [5.305721

In [0]:
## ANN
## DNN
## 