## 01.  Tensorflow 시작하기

### 1-1 라이브러리 불러오기

In [0]:
import tensorflow as tf

In [0]:
tf.__version__

'1.12.0'

In [0]:
### 값을 저장

In [0]:
strA = tf.constant("Hello, Tensorflow!")
print(strA)

Tensor("Const_1:0", shape=(), dtype=string)


In [0]:
## 실행
sess= tf.Session()
sess.run(strA)

b'Hello, Tensorflow!'

In [0]:
## 텐서플로워 연산 (+)
## 그래프의 구성 
a = tf.constant(10)
b = tf.constant(25)
c = tf.add(a,b)

print(c)
print(type(c))

Tensor("Add_1:0", shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.Tensor'>


## 3-2 그래프의 실행
 * 실제 연산 부분은 C++로 구현하였다.
 * 모델 구성과 실행을 분리해서 프로그램을 깔끔하게 작성.


In [0]:
sess = tf.Session()
print(sess.run([a,b,c]))

sess.close()

[10, 25, 35]


In [0]:
## 플레이스 홀더 선언
X = tf.placeholder(tf.float32, [None,3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [0]:
### 실행시에 넣을 데이터 x
x_data = [ [1,2,3], 
           [4,5,6] ]    # 2 X 3

In [0]:
# y = xw + b   -> (3 x 3) x (3 x 2) + (? x 1)
# 2 2 + 
# 2 1 
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))
print(W)
print(b)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32_ref>
<tf.Variable 'Variable_1:0' shape=(2, 1) dtype=float32_ref>


In [0]:
### 수식계산 matrix multiplication
expr = tf.matmul(X, W) + b
expr

<tf.Tensor 'add:0' shape=(2, 2) dtype=float32>

### 연산 실행 및 결과 출력

In [0]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(x_data) # python 문법 
print("===== W matrix =====")
print(sess.run(W))
print("===== b =====")
print(sess.run(b))
print("=== expr ====")
print(sess.run(expr, feed_dict={X:x_data}))

sess.close()

[[1, 2, 3], [4, 5, 6]]
===== W matrix =====
[[ 0.04773103  0.59383506]
 [ 0.6350212  -1.0228595 ]
 [-1.4559773   0.98496073]]
===== b =====
[[-0.94644004]
 [ 0.6420741 ]]
=== expr ====
[[-3.9965985  0.5565583]
 [-4.72776    3.8128815]]


In [0]:
##

In [0]:
import tensorflow as tf

In [3]:
tf.__version__

'1.12.0'

In [0]:
## 값을 저장

In [5]:
strA = tf.constant('Hello, Tensorflow!')
print(strA)

Tensor("Const:0", shape=(), dtype=string)


In [6]:
## 실행
sess = tf.Session()
sess.run(strA)

b'Hello, Tensorflow!'

In [7]:
## 텐서플로우 연산 (+)
## 그래프의 구성
a = tf.constant(10)
print(a)

Tensor("Const_1:0", shape=(), dtype=int32)


In [8]:
b= tf.constant(25)
print(b)

Tensor("Const_2:0", shape=(), dtype=int32)


In [9]:
c = tf.add(a,b)
print(c)
print(type(c))

Tensor("Add:0", shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.Tensor'>


In [17]:
sess = tf.Session()
print(sess.run([a,b,c]))

sess.close()

[10, 25, 35]


In [18]:
## 플레이스 홀더 선언
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [0]:
### 실행시에 넣을 테이터 x
x_data = [[1,2,3],
         [4,5,6]]

In [20]:
x_data

[[1, 2, 3], [4, 5, 6]]

In [21]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))
print(W)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32_ref>


In [22]:
print(b)

<tf.Variable 'Variable_1:0' shape=(2, 1) dtype=float32_ref>


In [23]:
### 수식계산 matrix multiplication
expr = tf.matmul(X, W) +b
expr

<tf.Tensor 'add_1:0' shape=(2, 2) dtype=float32>

In [31]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(x_data) # 파이썬 문법
print('=== W matrix ===')
print(sess.run(W))
print('=== b ===')
print(sess.run(b))
print('=== expr ===')
print(sess.run(expr, feed_dict={X:x_data}))

sess.close()

[[1, 2, 3], [4, 5, 6]]
=== W matrix ===
[[-0.34295613  1.8190753 ]
 [-0.38536116 -0.8717073 ]
 [-1.4469494   1.314598  ]]
=== b ===
[[-0.6652114 ]
 [ 0.09643319]]
=== expr ===
[[ -6.1197376   3.354243 ]
 [-11.883893   10.901786 ]]


In [0]:
##

In [0]:
import tensorflow as tf

In [0]:
x_data = [1, 2 ,3]
y_data = [1, 2, 3]

In [0]:
# w와 b를 각각 -1~1 사이의 균등분포를 갖는 무작위 값으로 초기화 수행

In [36]:
W =tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
print(W)

<tf.Variable 'Variable_2:0' shape=(1,) dtype=float32_ref>


In [37]:
print(b)

<tf.Variable 'Variable_3:0' shape=(1,) dtype=float32_ref>


In [0]:
## 2-3 플레이스 홀더 설정

In [39]:
T = tf.placeholder(tf.float32)
print(T)

Tensor("Placeholder_1:0", dtype=float32)


In [40]:
X1 = tf.placeholder(tf.float32, name='X')
Y1 = tf.placeholder(tf.float32, name='Y')
print(X1)
print(Y1)

Tensor("X:0", dtype=float32)
Tensor("Y:0", dtype=float32)


In [0]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.close()

In [0]:
### hypothesis = W*X +b
hypothesis = W*X1 +b

In [0]:
# 손실함수(loss function)
## 데이터에 대한 손실값을 계산하는 함수
## 경사하강법은 최적화 방법 중 가장 기본적인 알고리즘
## 경사하강법 : 함수의 기울기를 구하고, 기울기가 낮은 쪽으로 이동시켜가며 최적 값을 찾아간다.

In [45]:
cost = tf.reduce_mean(tf.square(hypothesis - Y1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)
train_op

<tf.Operation 'GradientDescent' type=NoOp>

In [0]:
# learning_rate는 학습을 얼마나 급하게 할 것인가를 설정함
# 학습을 진행하는 과정 중에 영햐을 주는 변수를 하이퍼파라미터라고 한다.
# 하이퍼 파라미터를 어떻게 찾는가에 따라 학습속도와 신경망 성능이 달라질 수 있다.

In [0]:
# hypothesis = W*X1+b # name:X1
# cost = tf.reduce_mean(tf.square(hypothesis - Y1)) # name:Y1
# x_data = [1,2,3]
# y_data = [1,2,3]
# optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
# train_op = optimizer.minimize(cost)

In [0]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [49]:
for step in range(100):
  _, cost_val= sess.run([train_op, cost], feed_dict={X1:x_data, Y1:y_data})
  if step%10==0:
    print(step, cost_val, sess.run(W), sess.run(b))
    
print('X1:5, Y1:', sess.run(hypothesis, feed_dict={X1:5}))

0 7.685257 [0.65259874] [1.1057279]
10 0.10294083 [0.6363177] [0.8267353]
20 0.0632753 [0.7148684] [0.6481711]
30 0.038893834 [0.77645314] [0.50817454]
40 0.023907112 [0.82473636] [0.39841542]
50 0.0146951275 [0.8625911] [0.31236282]
60 0.00903274 [0.8922696] [0.24489647]
70 0.005552213 [0.91553795] [0.192002]
80 0.0034128132 [0.9337807] [0.15053208]
90 0.0020977769 [0.9480832] [0.11801907]
X1:5, Y1: [4.8862777]


In [0]:
# 기본 신경망 구현
# y = sigmoid(X*W + b)
# y : 출력
# sigmoid : Activation function(활성화 함수)
# X : 입력
# W : 가중치(weight)
# b : 편향(bias)

In [0]:
# 학습이란 W, b 값을 찾아내는 것
# 최적화 알고리즘 : GradientDescent(경사하강법)

In [0]:
## 활성화 함수(Activation function)
# 활성화 함수(activation function)는 인공 신경망을 통해 들어온 값을 최종적으로 어떤 값으로 만들지 결정한다.
# 종류 : Sigmoid(시그모이드), ReLu(렐루), tanh(쌍곡탄젠트), Softmax(소프트맥스)

In [0]:
import tensorflow as tf

In [54]:
tf.__version__

'1.12.0'

In [0]:
## 값을 저장

In [56]:
strA=tf.constant('Hello, Tensorflow!')
print(strA)

Tensor("Const_3:0", shape=(), dtype=string)


In [57]:
## 실행
sess = tf.Session()
sess.run(strA)

b'Hello, Tensorflow!'

In [58]:
## 텐서플로우 연산 (+)
## 그래프의 구성
a=tf.constant(10)
b=tf.constant(25)
c=tf.add(a,b)

print(c)
print(type(c))

Tensor("Add_3:0", shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.Tensor'>


In [0]:
## 그래프 실행
# 실제 연산 부분은 C++로 구현하였다.
# 모델 구성과 실행을 분리해서 프로그램을 깔끔하게 작성.

In [60]:
sess = tf.Session()
print(sess.run([a,b,c]))
sess.close()

[10, 25, 35]


In [61]:
## 플레이스 홀더 선언
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder_2:0", shape=(?, 3), dtype=float32)


In [0]:
## 실행시에 넣을 데이터 x
x_data = [[1,2,3], [4,5,6]]

In [63]:
# y = xw + b -> (3*3) * (3*3) + (?*1)
# 2 2 +
# 2 1
W = tf.Variable(tf.random_normal([3,2]))
b=tf.Variable(tf.random_normal([2,1]))
print(W)
print(b)

<tf.Variable 'Variable_4:0' shape=(3, 2) dtype=float32_ref>
<tf.Variable 'Variable_5:0' shape=(2, 1) dtype=float32_ref>


In [64]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))
print(W)
print(b)

<tf.Variable 'Variable_6:0' shape=(3, 2) dtype=float32_ref>
<tf.Variable 'Variable_7:0' shape=(2, 1) dtype=float32_ref>


In [65]:
## 수식 계산 matrix multiplication
expr = tf.matmul(X, W) + b
expr

<tf.Tensor 'add_4:0' shape=(2, 2) dtype=float32>

In [73]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(x_data) # 파이썬 문법
print('=== W matrix ===')
print(sess.run(W))
print('=== b ===')
print(sess.run(b))
print('=== expr ===')
print(sess.run(expr, feed_dict={X:x_data}))

sess.close()

[[1, 2, 3], [4, 5, 6]]
=== W matrix ===
[[-0.2142382   0.15353583]
 [-0.30554494  1.1878252 ]
 [ 0.5264364  -0.34624597]]
=== b ===
[[0.5229467]
 [0.6862877]]
=== expr ===
[[1.2769277 2.013395 ]
 [1.4602287 5.1620812]]


In [0]:
import tensorflow as tf

In [75]:
tf.__version__

'1.12.0'

In [0]:
## 값을 저장

In [77]:
strA = tf.constant('Hello Tensorflow')
print(strA)

Tensor("Const_6:0", shape=(), dtype=string)


In [78]:
# 텐서플로우 연산 (+)
# 그래프 구성
a = tf.constant(10)
b = tf.constant(25)
c = tf.add(a,b)

print(c)
print(type(c))

Tensor("Add_5:0", shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.Tensor'>


In [0]:
# 그래프의 실행
## 실제 연산 부분은 C++로 구현
## 모델 구성과 실행을 분리해서 프로그램 작성

In [80]:
sess = tf.Session()
print(sess.run([a,b,c]))

[10, 25, 35]


In [81]:
# 플레이스 홀더 선언
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder_3:0", shape=(?, 3), dtype=float32)


In [0]:
# 실행시 넣을 데이터 x
x_data = [[1,2,3], [4,5,6]]

In [84]:
# y=xw + b -> (3*3)*(3*2)+(?*1)
# 2 2 +
# 2 1
W =tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))
print(W)
print(b)

<tf.Variable 'Variable_10:0' shape=(3, 2) dtype=float32_ref>
<tf.Variable 'Variable_11:0' shape=(2, 1) dtype=float32_ref>


In [86]:
# 수식 계산 matrix multiplication
expr = tf.matmul(X, W)+b
expr

<tf.Tensor 'add_7:0' shape=(2, 2) dtype=float32>

In [87]:
# 연산 실행 및 결과 출력
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(x_data)

[[1, 2, 3], [4, 5, 6]]


In [88]:
print(sess.run(W))

[[ 0.15645334  0.1032697 ]
 [ 0.435112   -1.5176002 ]
 [-0.4267376  -0.9012546 ]]


In [89]:
print(sess.run(b))

[[0.8991574]
 [0.5936832]]


In [90]:
print(sess.run(expr, feed_dict={X:x_data}))

[[  0.64562196  -4.736537  ]
 [  0.834631   -11.988767  ]]


In [0]:
import tensorflow as tf

In [92]:
tf.__version__

'1.12.0'

In [93]:
## 값을 저장
strA = tf.constant('Hello, Tensorflow')
print(strA)

Tensor("Const_9:0", shape=(), dtype=string)


In [94]:
# 실행
sess = tf.Session()
sess.run(strA)

b'Hello, Tensorflow'

In [95]:
# 텐서플로우 연산 (+)
## 그래프의 구성
a = tf.constant(10)
b = tf.constant(25)
c = tf.add(a,b)

print(c)
print(type(c))

Tensor("Add_8:0", shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.Tensor'>


In [0]:
# 그래프의 실행
## 실제 연산 부분은 C++로 구현
## 모델 구성과 실행을 분리해서 프로그램을 깔끔하게 작성

In [97]:
sess = tf.Session()
print(sess.run([a,b,c]))

sess.close()

[10, 25, 35]


In [0]:
# 실행시에 넣을 데이터 x
x_data = [[1,2,3], [4,5,6]]

In [99]:
# y=xw + b -> (3 x 3) x (3 x 2) + (? x 1)
# 2 2 +
# 2 1
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))
print(W)
print(b)

<tf.Variable 'Variable_12:0' shape=(3, 2) dtype=float32_ref>
<tf.Variable 'Variable_13:0' shape=(2, 1) dtype=float32_ref>


In [100]:
# 수식 계산 matrix multiplication
expr = tf.matmul(X, W)+b
expr

<tf.Tensor 'add_9:0' shape=(2, 2) dtype=float32>

In [101]:
# 연산 실행 및 결과 출력
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(x_data)

[[1, 2, 3], [4, 5, 6]]


In [102]:
print(sess.run(W))

[[-0.53459907 -0.47492844]
 [-0.8497459  -0.45109686]
 [ 1.2394621  -0.91072094]]


In [103]:
print(sess.run(b))

[[1.252672 ]
 [1.5756165]]


In [104]:
print(sess.run(expr, feed_dict={X:x_data}))

[[ 2.7369676 -2.856613 ]
 [ 2.6252632 -8.043907 ]]


In [0]:
sess.close()

In [0]:
# 선형 회귀 모델 구현

In [0]:
import tensorflow as tf

In [0]:
x_data = [1,2,3]
y_data = [1,2,3]

In [0]:
# w와 b를 각각 -1~1 사이의 균등분포를 갖는 무작위 값으로 초기화 수행

In [111]:
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
print(W)
print(b)

<tf.Variable 'Variable_14:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'Variable_15:0' shape=(1,) dtype=float32_ref>


In [0]:
# 플레이스 홀더 설정

In [113]:
T = tf.placeholder(tf.float32)
print(T)

Tensor("Placeholder_4:0", dtype=float32)


In [114]:
X1 = tf.placeholder(tf.float32, name='X')
Y1 = tf.placeholder(tf.float32, name='Y')
print(X1)
print(Y1)

Tensor("X_1:0", dtype=float32)
Tensor("Y_1:0", dtype=float32)


In [0]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.close()

In [0]:
# hypothesis = W*X +b
hypothesis = W*X1+b

In [0]:
# 손실함수(loss function)
## 데이터에 대한 손실값을 계산하는 함수
## 경사하강법(Gradient Descent)는 최적화 방법 중 가장 기본적인 알고리즘
## 경사하강법: 함수의 기울기를 구하고, 기울기가 낮은 쪽으로 이동시켜가며 최적의 값을 찾는다/

In [119]:
cost = tf.reduce_mean(tf.square(hypothesis - Y1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)
train_op

<tf.Operation 'GradientDescent_1' type=NoOp>

In [0]:
# learning_rate 는 학습을 얼마나 급하게 할 것인가 설정
# 학습을 진행하는 과정 중에 영향을 주는 변수를 하이퍼파라미터라 한다.
# 하이퍼 파라미터를 어떻게 찾는가에 따라 학습속도와 신경망 성능이 달라질 수 있다.

In [0]:
# hypothesis = W*X1+b # name : X
# cost = tf.reduce_mean(tf.square(hypothesis - Y1)) # name: Y
# x_data = [1,2,3]
# y_data = [1,2,3]
# optimizer = tf.train.GradientDescentOptimizer(leanring_rate=0.1)
# train_op = optimizer.minimizer(cost)

In [122]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(100):
  _, cost_val = sess.run([train_op, cost], feed_dict={X1:x_data, Y1:y_data})
  if step%10 ==0:
    print(step, cost_val, sess.run(W), sess.run(b))
    
print('X1:5, Y1:', sess.run(hypothesis, feed_dict={X1:5}))


0 14.092304 [0.9356985] [0.5782253]
10 0.023906967 [0.82473683] [0.3984144]
20 0.014695068 [0.8625914] [0.31236202]
30 0.009032713 [0.8922699] [0.24489588]
40 0.0055521857 [0.9155382] [0.19200154]
50 0.0034128062 [0.9337809] [0.15053172]
60 0.002097769 [0.94808334] [0.11801881]
70 0.0012894458 [0.9592967] [0.09252826]
80 0.00079259387 [0.9680881] [0.07254334]
90 0.0004871868 [0.9749806] [0.0568749]
X1:5, Y1: [4.9451957]


In [0]:
# 선형 회귀 모델 구현하기
import tensorflow as tf

In [0]:
x_data = [1,2,3]
y_data = [1,2,3]

In [0]:
# W와 b를 각각 -1~1 사이의 균등분포를 갖는 무작위 값으로 초기화 수행

In [0]:
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

In [127]:
print(W)
print(b)

<tf.Variable 'Variable_16:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'Variable_17:0' shape=(1,) dtype=float32_ref>


In [128]:
T=tf.placeholder(tf.float32)
print(T)

Tensor("Placeholder_5:0", dtype=float32)


In [129]:
X1 = tf.placeholder(tf.float32, name='X')
Y1 = tf.placeholder(tf.float32, name='Y')
print(X1)
print(Y1)

Tensor("X_2:0", dtype=float32)
Tensor("Y_2:0", dtype=float32)


In [0]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.close()

In [0]:
# hypothesis = W*X + b
hypothesis = W*X1 + b

In [0]:
# 손실함수(loss function)
## 데이터에 대한 손실값을 계산하는 함수
## 경사하강법(gradient descent)는 최적화 방법 중 가장 기본적인 알고리즘
## 경사하강법: 함수의 기울기를 구하고, 기울기가 낮은 쪽으로 이동시켜가면서 최적의 값을 찾아 나간다.

In [133]:
cost = tf.reduce_mean(tf.square(hypothesis - Y1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)
train_op

<tf.Operation 'GradientDescent_2' type=NoOp>

In [0]:
# learning_rate는 학습을 ㅓㄹ마나 급하게 할 것인가를 설정
# 학습을 진행하는 과정 중에 영향을 주는 변수를  하이퍼파라미터라 한다.
# 하이퍼 파라미터를 어떻게 찾는가에 따라 학습속도와 신경망 성능이 달라질 수 있다.

In [0]:
# hypothesis = W*X1+ b # name :X
# cost = tf.reduce_mean(th.square(hypothesis - Y1)) # name:Y
# x_data = [1,2,3]
# y_data = [1,2,3]
# optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
# train_op = optimizer.minimize(cost)

In [137]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(100):
  _, cost_val = sess.run([train_op, cost], feed_dict={X1:x_data, Y1:y_data})
  if step%10==0:
    print(step, cost_val, sess.run(W), sess.run(b))
    
print('X1:5, Y1:', sess.run(hypothesis, feed_dict={X1:5}))

0 0.66305554 [1.0421648] [-0.00200652]
10 2.745895e-05 [1.0059397] [-0.01350246]
20 1.6878002e-05 [1.0046569] [-0.01058612]
30 1.03748725e-05 [1.003651] [-0.0082997]
40 6.377213e-06 [1.0028625] [-0.00650711]
50 3.9200218e-06 [1.0022442] [-0.00510167]
60 2.4093845e-06 [1.0017595] [-0.00399971]
70 1.480887e-06 [1.0013795] [-0.0031358]
80 9.102958e-07 [1.0010815] [-0.00245851]
90 5.5958895e-07 [1.0008478] [-0.00192746]
X1:5, Y1: [5.0018573]


In [0]:
# 선형 회귀 모델 구현하기
import tensorflow as tf

In [0]:
x_data = [1,2,3]
y_data = [1,2,3]

In [0]:
# W와 b를 각각 -1~1사이의 균등분포를 갖는 무작위 값으로 초기화 수행

In [141]:
strA = tf.constant('Hello, Tensorflow')
print(strA)

Tensor("Const_12:0", shape=(), dtype=string)


In [142]:
# 실행
sess = tf.Session()
sess.run(strA)

b'Hello, Tensorflow'

In [143]:
## 텐서플로우 연산 (+)
## 그래프의 구성
a=tf.constant(10)
b=tf.constant(25)
c=tf.add(a,b)

print(c)
print(type(c))

Tensor("Add_12:0", shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.Tensor'>


In [0]:
# 그래프의 실행
## 실제 연산 부분은 C++로 구현
## 모델 구성과 실행을 분리해서 프로그램을 깔끔하게 작성

In [145]:
sess = tf.Session()
print(sess.run([a,b,c]))

sess.close()

[10, 25, 35]


In [0]:
# 실행시에 넣을 데이터 x
x_data = [[1,2,3], [4,5,6]]