## 01. Tensorflow에서의 변수 표현

In [0]:
import tensorflow as tf

In [0]:
# 상수 정의할 때, 
a1 = tf.constant(10, name="a")
b1 = tf.constant(20, name="b")
c1 = tf.constant(30, name="c")

In [0]:
# 변수 정의하기 
v = tf.Variable(0, name='v')  # 변수 v선언하고 초기값 0

In [0]:
# 데이터 플로우 그래프 정의, 그래프를 실행
calc_op = a1 + b1 + c1
assign_op = tf.assign(v, calc_op) # v에 calc_op 대입

In [0]:
# 세션을 실행
sess = tf.Session()
sess.run(assign_op)

60

In [0]:
sess.run(v)

60

## 02. 플레이스 홀더(Placeholder)

* 템플릿처럼 값을 넣을 공간을 만들어둔다.
* 플레이스 홀더를 이용하면 데이터 플로우 그래프를 구축시에 값을 넣지 않고, 
* 세션을 실행시에 값을 넣을 수 있다.

In [0]:
# 플레이스 홀더 정의하기
a = tf.placeholder(tf.int32, [3])  # 정수 자료형 3개를 가진 배열

# 배열을 모든 값을 2배한다.
b = tf.constant(2)
x2_op = a * b

In [0]:
# 세션을 시작
sess = tf.Session() 
# 플레이스 홀더에 값을 넣고 실행.
r1 = sess.run(x2_op, feed_dict={ a:[1,2,3]    })
r2 = sess.run(x2_op, feed_dict={ a:[10,20,30] })
print(r1,r2)

[2 4 6] [20 40 60]


In [0]:
### 01. 5개의 배열을 갖는 값에 대해 3*, 3/, 3+, 3- 구하기 
### 02. 몇개의 배열(3,4,5) 
### 03. 2차원의 배열

In [0]:
c = tf.placeholder(tf.int32, [None] ) # 실수 자료형 ?개 가진 배열
b = tf.constant(3)
x2_op1 = c*b
x2_op2 = c+b
x2_op3 = c-b
x2_op4 = c/b

In [0]:
# 세션을 시작
sess = tf.Session() 
# 플레이스 홀더에 값을 넣고 실행.
r1 = sess.run(x2_op1, feed_dict={ c:[1,2,3]    })
r2 = sess.run(x2_op1, feed_dict={ c:[10,20,30,50,10] })
print(r1,r2)

[3 6 9] [ 30  60  90 150  30]


In [0]:
# 플레이스 홀더에 값을 넣고 실행.
r1 = sess.run(x2_op2, feed_dict={ c:[1,2,3]    })
r2 = sess.run(x2_op2, feed_dict={ c:[10,20,30,50,10] })
print(r1,r2)

[4 5 6] [13 23 33 53 13]


In [0]:
# 플레이스 홀더에 값을 넣고 실행.
r1 = sess.run(x2_op3a, feed_dict={ c:[1,2,3]    })
r2 = sess.run(x2_op3, feed_dict={ c:[10,20,30,50,10] })
print(r1,r2)

[-2 -1  0] [ 7 17 27 47  7]


In [0]:
# 플레이스 홀더에 값을 넣고 실행.
r1 = sess.run(x2_op4, feed_dict={ c:[1,2,3]    })
r2 = sess.run(x2_op4, feed_dict={ c:[10,20,30,50,10] })
print(r1,r2)

[0.33333333 0.66666667 1.        ] [ 3.33333333  6.66666667 10.         16.66666667  3.33333333]


In [0]:
!ls

bmi.csv  sample_data


In [0]:
!mv bmi.csv bmi1.csv

In [0]:
!ls

bmi1.csv  sample_data
