### 1-1 1차원 배열 간의 [10, 10], [3, 5] 의 행렬의 내적(dot)를 구해보자.

In [0]:
import math
import numpy as np

In [2]:
d = np.array([10, 10])
e = np.array([3, 5])
print(np.dot(d,e))

80


### 아래 행렬에 대한 연산을 numpy를 이용하여 계산해 보자.

#### (가) 2를 곱하기

In [3]:
d = np.array([[5,3], [2, 1]])
print(2*d)

[[10  6]
 [ 4  2]]


#### (나) 행렬의 덧셈

In [4]:
d = np.array([[5, 3], [2, 1]])
e = np.array([[5, 3], [2, 1]])
print(d+e)

[[10  6]
 [ 4  2]]


### 1-2 Tensorflow는 그래프의 생성과 그래프의 실행으로 나눌 수 있다. 아래 내용에 따라 파이썬 프로그램을 작성해 보자.

(1) 두 개의 값을 선언하고 이에 대한 곱에 대한 결과를 확인해 보자.<br>
(가) a=15, b=30의 값을 저장한다.<br>
(나) c는 두 값의 곱의 값을 저장한다.<br>
(다) 값을 확인하기 위한 세션을 선언하고 이를 실행하여 a, b, c의 값을 확인한다.<br>

In [11]:
import tensorflow as tf

a = tf.constant(15)
b = tf.constant(30)
c = tf.multiply(a,b)
print(c)

Tensor("Mul_3:0", shape=(), dtype=int32)


In [13]:
sess = tf.Session()
print('a = ', sess.run(a))
print('b = ', sess.run(b))
print('c = ', sess.run(c))
sess.close()

a =  15
b =  30
c =  450


### (2) 아래 행렬 연산을 수행하는 프로그램을 작성해 보자.

(가) R(임의 값) x 4의 행렬을 X를 선언한다. 내용은 실수 값을 갖는다.
(Tensor형, 플레이스 홀더)<br>
(나) W, b의 값을 random_norma를 이용하여 값을 지정
W : 4 x 3 , b : 2 x 1<br>
(다) Y = X * W + b를 만족시키는 식을 구하고, 이에 대한 결과를 확인해 보자.

In [0]:
X = tf.placeholder(tf.float32, [None, 5]) # R(임의의 데이터 행) * 4

In [0]:
x_data = [[3,4,5,6,7], [6,7,8,9,10], [1,2,3,4,5]]

In [0]:
W = tf.Variable(tf.random_normal([5,3]))
b = tf.Variable(tf.random_normal([3,1]))

In [0]:
Y_pred = tf.matmul(X, W) + b

In [41]:
# 그래프 실행
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print('==x_data==')
print(x_data)
print('==W matrix==')
print(sess.run(W))
print('==b==')
print(sess.run(b))
print('==Y_pred==')
print(sess.run(Y_pred, feed_dict={X:x_data})) # 플레이스 홀더로 되어 있는 부분은 feed_dict로 값을 넣어준다.

sess.close()

==x_data==
[[3, 4, 5, 6, 7], [6, 7, 8, 9, 10], [1, 2, 3, 4, 5]]
==W matrix==
[[ 0.16010955  1.7432028   0.36612764]
 [-0.12225422  1.6526129   1.0013729 ]
 [-0.526193    0.1930362   0.10986774]
 [ 1.1815568   1.3481311   0.12086853]
 [ 0.27211654 -0.13087441 -1.4193169 ]]
==b==
[[0.566554  ]
 [0.09946875]
 [1.710569  ]]
==Y_pred==
[[ 6.921057  20.54446   -2.9902396]
 [ 9.349979  34.4957    -2.9205654]
 [ 6.134401  12.076259  -2.2040644]]


### Tensorflow를 활용하여 단순/다중 선형회귀 모형을 구현해 보자.

(가) Learning rate(학습률)로 0.01로 지정한다.<br>
(나) 손실함수 (Loss) 함수를 10개 - cost 비용<br>
(다) 최적화 함수로 GradientDescent 알고리즘을 사용한다.<br>
(라) 학습이 수행될 때, 최소 10번에 한번꼴로 해당 loss와 W값이 출력
되도록 한다.<br>

(다중 선형 회귀 모형의 경우 약간의 가산점이 있음)

In [0]:
import tensorflow as tf
import numpy as np

In [0]:
x_data = [1,2,3,4,5]
y_data = [10, 20, 30, 40, 50]

In [63]:
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
print(W)
print(b)

<tf.Variable 'Variable_16:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'Variable_17:0' shape=(1,) dtype=float32_ref>


In [64]:
T = tf.placeholder(tf.float32)
print(T)

Tensor("Placeholder_6:0", dtype=float32)


In [65]:
X = tf.placeholder(tf.float32, name='X')
Y = tf.placeholder(tf.float32, name='Y')

print(X)
print(Y)

Tensor("X:0", dtype=float32)
Tensor("Y:0", dtype=float32)


In [0]:
hypothesis = W*X +b

In [67]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
cost

<tf.Tensor 'Mean_3:0' shape=() dtype=float32>

In [68]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)
print(train_op)

name: "GradientDescent_2"
op: "NoOp"
input: "^GradientDescent_2/update_Variable_16/ApplyGradientDescent"
input: "^GradientDescent_2/update_Variable_17/ApplyGradientDescent"



In [69]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  
  for step in range(100):
    _, cost_val = sess.run([train_op, cost], feed_dict={X:x_data, Y:y_data})
    print(step, cost_val, sess.run(W), sess.run(b))

0 1258.5676 [1.4002005] [1.5808764]
1 734.4499 [3.1973038] [2.0652468]
2 429.01318 [4.569982] [2.4321036]
3 251.01297 [5.61866] [2.7092626]
4 147.27644 [6.419999] [2.9179578]
5 86.81721 [7.0325217] [3.0743988]
6 51.57786 [7.500903] [3.1909595]
7 31.035452 [7.8592467] [3.277086]
8 19.05777 [8.133587] [3.3399894]
9 12.07121 [8.343799] [3.3851745]
10 7.993257 [8.505053] [3.4168432]
11 5.61036 [8.62893] [3.438203]
12 4.215303 [8.724274] [3.4517033]
13 3.3959396 [8.797832] [3.4592128]
14 2.9121113 [8.854755] [3.4621587]
15 2.6238685 [8.89898] [3.46163]
16 2.4496326 [8.933507] [3.4584587]
17 2.3418865 [8.960628] [3.453279]
18 2.272924 [8.982093] [3.4465759]
19 2.226604 [8.999238] [3.4387188]
20 2.193525 [9.0130825] [3.42999]
21 2.1681962 [9.024405] [3.4206052]
22 2.1474285 [9.033799] [3.4107287]
23 2.1293616 [9.041719] [3.4004862]
24 2.1129065 [9.048512] [3.3899734]
25 2.0974298 [9.054441] [3.3792632]
26 2.0825605 [9.059709] [3.3684113]
27 2.0680935 [9.064468] [3.3574605]
28 2.0538914 [9.068

In [70]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  
  for step in range(1000):
    _, cost_val = sess.run([train_op, cost], feed_dict={X:x_data, Y:y_data})
    if step%10==0:
      print(step, cost_val, sess.run(W), sess.run(b))
      
  print('X:5, Y:', sess.run(hypothesis, feed_dict={X:5}))
  print('X:2.5, Y:', sess.run(hypothesis, feed_dict={X:2.5}))

0 1101.9889 [2.3769758] [-0.07071327]
10 5.5896354 [9.015468] [1.7000862]
20 0.5973676 [9.477344] [1.7623253]
30 0.53735167 [9.523586] [1.7116282]
40 0.5020658 [9.541389] [1.6551679]
50 0.46918482 [9.556791] [1.6000874]
60 0.43845606 [9.571558] [1.5468068]
70 0.40974307 [9.585826] [1.4952989]
80 0.38290802 [9.599619] [1.4455056]
90 0.3578311 [9.61295] [1.3973703]
100 0.33439723 [9.625839] [1.3508383]
110 0.31249633 [9.638299] [1.3058555]
120 0.29202992 [9.650344] [1.2623707]
130 0.27290532 [9.661986] [1.2203342]
140 0.25503275 [9.673242] [1.179698]
150 0.23833081 [9.684124] [1.140414]
160 0.2227219 [9.694642] [1.1024384]
170 0.20813553 [9.704811] [1.0657272]
180 0.19450472 [9.714641] [1.0302387]
190 0.18176678 [9.724143] [0.99593174]
200 0.16986296 [9.733329] [0.9627674]
210 0.15873827 [9.7422085] [0.93070763]
220 0.1483424 [9.750793] [0.8997153]
230 0.13862756 [9.759092] [0.86975485]
240 0.12954883 [9.767114] [0.84079206]
250 0.12106422 [9.77487] [0.8127937]
260 0.113135144 [9.782366]

In [61]:
#########
# 결과 확인
# 0: 기타 1: 포유류, 2: 조류
######
# tf.argmax: 예측값과 실제값의 행렬에서 tf.argmax 를 이용해 가장 큰 값을 가져옵니다.
# 예) [[0 1 0] [1 0 0]] -> [1 0]
# [[0.2 0.7 0.1] [0.9 0.1 0.]] -> [1 0]
prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)
print('예측값:', sess.run(prediction, feed_dict={X: x_data}))
print('실제값:', sess.run(target, feed_dict={Y: y_data}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('정확도: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_data, Y: y_data}))

예측값: [0 2 2 0 0 2]
실제값: [0 1 2 0 0 2]
정확도: 83.33
