# 능력단위 평가 - 딥러닝

### 실습 과제 1-1 [기본항목 1-3, 1-4] – 10점

#### 1차원 배열 간의 [10, 10], [3, 5] 의 행렬의 내적(dot)를 구해보자.

In [1]:
import math
import numpy as np

In [2]:
d = np.array([10, 10])
e = np.array([3, 5])
print(np.dot(d, e))

80


#### 아래 행렬에 대한 연산을 numpy를 이용하여 계산해 보자.

##### (가) 2를 곱하기

In [4]:
d = np.array([[5,3], [2,1]])
print(d)
print(2*d)

[[5 3]
 [2 1]]
[[10  6]
 [ 4  2]]


##### (나) 행렬의 덧셈

In [10]:
d = np.array([[5,3], [2,1]])
e = np.array([[5,3], [2,1]])
print(d+e)

[[10  6]
 [ 4  2]]


In [8]:
d

array([list([5.3]), list([2, 1])], dtype=object)

### 1-2 Tensorflow는 그래프의 생성과 그래프의 실행으로 나눌 수 있다. 아래 내용에 따라 파이썬 프로그램을 작성해 보자.

#### (1) 두 개의 값을 선언하고 이에 대한 곱에 대한 결과를 확인해 보자.<br>
(가) a=15, b=30의 값을 저장한다.<br>
(나) c는 두 값의 곱의 값을 저장한다.<br>
(다) 값을 확인하기 위한 세션을 선언하고 이를 실행하여 a, b, c의 값을 확인한다.

In [12]:
import tensorflow as tf

a = tf.constant(15)
b = tf.constant(30)
c = tf.multiply(a, b)
print(c)

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Tensor("Mul:0", shape=(), dtype=int32)


In [13]:
sess  = tf.Session()
print('a = ', sess.run(a))
print('b = ', sess.run(b))
print('c = ', sess.run(c))
sess.close()

a =  15
b =  30
c =  450


#### (2) 아래 행렬 연산을 수행하는 프로그램을 작성해 보자.<br>

(가) R(임의 값) x 4의 행렬을 X를 선언한다. 내용은 실수 값을 갖는다. (Tensor형, 플레이스 홀더)<br>
(나) W, b의 값을 random_norma를 이용하여 값을 지정 W : 4 x 3 , b : 3 x 1<br>
(다) Y = X * W + b를 만족시키는 식을 구하고, 이에 대한 결과를 확인해 보자

In [17]:
X = tf.placeholder(tf.float32, [None, 4])

In [18]:
x_data = [[3,4,5,6], [7,8,9,10], [1,2,3,4]]

In [19]:
W = tf.Variable(tf.random_normal([4, 3]))
b = tf.Variable(tf.random_normal([3, 1]))

In [20]:
Y_pred = tf.matmul(X, W) + b

In [21]:
# 그래프 실행
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print('--x_data--')
print(x_data)
print('--W matrix--')
print(sess.run(W))
print('--Y_pred--')
print(sess.run(Y_pred, feed_dict={X:x_data}))

sess.close()

--x_data--
[[3, 4, 5, 6], [7, 8, 9, 10], [1, 2, 3, 4]]
--W matrix--
[[ 0.4048495   0.9868611   0.39601076]
 [ 0.04500555  0.12342189 -0.8719522 ]
 [-0.08563911 -0.668734    0.29411003]
 [ 0.17409867  0.38429895 -1.4154762 ]]
--Y_pred--
[[  2.5959365   3.001364   -8.737114 ]
 [  5.037427    6.5929875 -14.838113 ]
 [  1.7701788   1.6005396  -5.2916274]]


### Tensorflow를 활용하여 단순/다중 선형회귀 모형을 구현해 보자.

(가) Learning rate(학습률)로 0.01로 지정한다.<br>
(나) 손실함수 (Loss) 함수를 10개 - cost 비용<br>
(다) 최적화 함수로 GradientDescent 알고리즘을 사용한다.<br>
(라) 학습이 수행될 때, 최소 10번에 한번꼴로 해당 loss와 W값이 출력 되도록 한다.<br>

(다중 선형 회귀 모형의 경우 약간의 가산점이 있음)

In [22]:
import tensorflow as tf
import numpy as np

In [23]:
x_data = [1,2,3,4,5]
y_data = [10, 20, 30, 40, 50]

In [25]:
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
print(W)
print(b)

<tf.Variable 'Variable_4:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'Variable_5:0' shape=(1,) dtype=float32_ref>


In [28]:
T = tf.placeholder(tf.float32)
print(T)

Tensor("Placeholder_2:0", dtype=float32)


In [29]:
X = tf.placeholder(tf.float32, name='X')
Y = tf.placeholder(tf.float32, name='Y')

print(X)
print(Y)

Tensor("X:0", dtype=float32)
Tensor("Y:0", dtype=float32)


In [30]:
hypothesis = W*X +b

In [31]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
cost

<tf.Tensor 'Mean:0' shape=() dtype=float32>

In [32]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)
print(train_)

name: "GradientDescent"
op: "NoOp"
input: "^GradientDescent/update_Variable_4/ApplyGradientDescent"
input: "^GradientDescent/update_Variable_5/ApplyGradientDescent"



In [33]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, sess.run(W), sess.run(b))

0 897.67615 [2.7372265] [1.3346624]
1 523.84784 [4.2549567] [1.7437356]
2 305.99432 [5.414242] [2.0535634]
3 179.0352 [6.299895] [2.2876375]
4 105.04486 [6.97666] [2.463891]
5 61.92212 [7.4939613] [2.5960135]
6 36.78756 [7.889529] [2.6944556]
7 22.135632 [8.192165] [2.7671947]
8 13.592511 [8.423858] [2.8203208]
9 8.60932 [8.60139] [2.858483]
10 5.7007194 [8.737576] [2.88523]
11 4.001111 [8.8421955] [2.903271]
12 3.0060875 [8.922716] [2.9146738]
13 2.4216857 [8.9848385] [2.9210174]
14 2.0765972 [9.032913] [2.9235067]
15 1.8710079 [9.070262] [2.9230618]
16 1.7467407 [9.099421] [2.920385]
17 1.6698964 [9.122325] [2.916012]
18 1.6207078 [9.140452] [2.9103522]
19 1.5876757 [9.154932] [2.903718]
20 1.5640838 [9.166624] [2.8963478]
21 1.5460203 [9.176186] [2.8884234]
22 1.5312132 [9.184119] [2.8800838]
23 1.5183269 [9.190808] [2.871435]
24 1.5065958 [9.196545] [2.8625576]
25 1.4955591 [9.201551] [2.8535137]
26 1.4849561 [9.205999] [2.8443503]
27 1.4746408 [9.210018] [2.8351033]
28 1.4645154 [

In [34]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(1000):
        _, cost_val = sess.run([train_op, cost], feed_dict={X:x_data, Y:y_data})
        if step%10==0:
            print(step, cost_val, sess.run(W), sess.run(b))
            
    print('X:5, Y:', sess.run(hypothesis, feed_dict={X:5}))
    print('X:2.5, Y:', sess.run(hypothesis, feed_dict={X:2.5}))

0 952.42224 [2.7884653] [0.38886172]
10 5.13899 [8.963154] [2.0196865]
20 0.8055199 [9.396522] [2.0629044]
30 0.7347125 [9.443422] [2.0016346]
40 0.6865124 [9.463758] [1.9354796]
50 0.6415541 [9.481736] [1.8710622]
60 0.59953576 [9.499002] [1.808758]
70 0.56027347 [9.515686] [1.7485273]
80 0.5235802 [9.531814] [1.6903019]
90 0.48929128 [9.547404] [1.634015]
100 0.45724684 [9.562475] [1.5796025]
110 0.42730156 [9.577045] [1.5270023]
120 0.39931673 [9.591128] [1.4761535]
130 0.37316513 [9.604745] [1.4269979]
140 0.34872594 [9.617907] [1.3794788]
150 0.3258883 [9.63063] [1.3335426]
160 0.30454478 [9.64293] [1.2891359]
170 0.28460088 [9.65482] [1.246208]
180 0.26596156 [9.666314] [1.2047096]
190 0.24854429 [9.677426] [1.1645931]
200 0.23226634 [9.688169] [1.1258122]
210 0.21705551 [9.698552] [1.0883228]
220 0.2028393 [9.7085905] [1.0520818]
230 0.18955615 [9.718294] [1.0170474]
240 0.17714128 [9.727675] [0.98317975]
250 0.16554078 [9.736743] [0.95044005]
260 0.15469906 [9.745509] [0.918790